### ISSUE TITLE
WDIO - Materials - Environment information in Allure report 

### ISSUE THREAD

**Issue by OleksandrBaior** [Luxe-Quality/docusaurus_issues#17]
**Allure Mocha**

For the main page of the report, you can collect various information about the environment in which the tests were executed.

For example, it is a good idea to use this to remember the OS version and Node.js version. This may help the future reader investigate bugs that are reproducible only in some environments.

```
import * as os from 'os';

export const config: Options.Testrunner = {

reporters: [
        [
            'allure',
            {
                outputDir: 'allure-results',
                disableWebdriverStepsReporting: true,
                disableWebdriverScreenshotsReporting: true,
                reportedEnvironmentVars: {
                    os_platform: os.platform(),
                    os_release: os.release(),
                    os_version: os.version(),
                    node_version: process.version,
                },
            },
        ],
    }
```

To provide environment information, put a file named environment.properties into the allure-results directory after running the tests. See the example in [Environment file](https://allurereport.org/docs/how-it-works-environment-file/).

**Note** that this feature should be used for properties that do not change for all tests in the report. If you have properties that can be different for different tests, consider using [Parametrized tests](https://allurereport.org/docs/mocha-reference/#parametrized-tests).

![chrome_CDvQpQUStg](https://github.com/Luxe-Quality/docusaurus_issues/assets/43751093/906ee9f5-8097-42ac-9f66-3ce90adde19a)

**Comment by zefirlover** [comment]
Стандартні налаштування are just fine та годяться для практично всіх ситуацій, тому поки жодного оновлення інформації про allure не передбачається
