### ISSUE TITLE
WDIO - Materials - Organize tests in Allure report

### ISSUE THREAD

**Issue by OleksandrBaior** [Luxe-Quality/docusaurus_issues#18]
As described in [Improving navigation in your test report](https://allurereport.org/docs/gettingstarted-navigation/), Allure supports multiple ways to organize tests into hierarchical structures.

To specify a test's location in the [behavior-based hierarchy](https://allurereport.org/docs/gettingstarted-navigation/#behavior-based-hierarchy):

```
const { allure } = require("allure-mocha/runtime");

it("behavior", () => {
  allure.epic("Web interface");
  allure.feature("Essential features");
  allure.story("Labels");
  // ...
});
```

**Behavior-based hierarchy**

Epics, features and user stories are widely-used terms for describing a software's features and organizing tests for said features. Usually, an epic is a large set of features that the team aims to develop and test, and a feature is described as a set of user stories that describe how the software is expected to behave in different scenarios.

Allure adapters for all test frameworks provide ways to indicate a test's epic, feature and user story. If a test framework lets the author define some of these terms natively, e.g., in its own language-agnostic file format, then Allure tries its best to incorporate the provided data into the generated tree structure. See the specific Allure adapter's documentation for more details.

![chrome_xyXPyodo1E](https://github.com/Luxe-Quality/docusaurus_issues/assets/43751093/c1a028fc-e966-4f08-aeb9-f375767eee98)

**Comment by zefirlover** [comment]
Стандартні налаштування are just fine та годяться для практично всіх ситуацій, тому поки жодного оновлення інформації про allure не передбачається
