### ISSUE TITLE
Assessment requirements for the task є ну в усіх розділах Task в Trainee program

### ISSUE THREAD

**Issue by VladysZav** [Luxe-Quality/docusaurus_issues#2]
![Screenshot_12](https://github.com/Luxe-Quality/docusaurus_issues/assets/108288355/8c46785c-9cd2-4f78-b94e-238a83e6c67a)

Не в усіх Task є Assessment requirements for the task, може у кожну таску додати цей розділ.

**Comment by zefirlover** [comment]
@Diankavoy19 глянь, будь-ласка, де Assessment requirements немає та додай їх туди. Завдання з Code Review можеш, поки що, проігнорувати
