### ISSUE TITLE
Не вказано яку мову програмування використовувати в тасках в Trainee program

### ISSUE THREAD

**Issue by VladysZav** [Luxe-Quality/docusaurus_issues#4]
![Screenshot_14](https://github.com/Luxe-Quality/docusaurus_issues/assets/108288355/f73edb0b-a2d9-442b-8e44-c54b461c9c85)
Вказано що можно використовувати будь яку мову програмування тільки в Task 2. Може треба указати це в Introduction, щоб точно було зрозуміло, що це правило діє на всі таски, а не тільки на першу

**Comment by zefirlover** [comment]
Як мінімум треба Type Script написати разом, а не окремо. Поки що чіпати більше нічого не треба
